- hosts: "{{ env }}"
  become: yes
  tasks: 
    - name: remove any previous app services
      shell: | 
         if [ `docker  ps | grep -v NAME | grep project1 | awk '{print $1}' | wc -l` -gt 0 ]; then  
            docker stop `docker ps | grep -v NAME | grep project1 | awk '{print $1}'`
         else 
            echo "No process found"
         fi
